
/**
 * The following block enables column H to override an expected message for the
 * report generated by the action or assertion
 * The behavior is following:
 * If H contains some text - this will be put into report
 * If H is empty - default message will be used
 * If H is equal to "---" - nothing is written to the report (no echo from action)
 */

//#region ReportColumn

var g_controlColumnForReport = "H";
var g_assertMessage = null;
var g_assertData = null;

OnRVLScriptStep=function(item, place, status, ctx, stackItem)
{
	var row = item.Startrow;
	if(row.Ext&&row.Ext[g_controlColumnForReport])
	{
		var h = row.Ext[g_controlColumnForReport];
		if( 
			( place == "before" && h )
		)
		{
			SetReportMsg(h);
		} 
	}
	
}

function SetReportMsg(/**string*/msg)
{
	g_assertMessage = msg;
}

Tester._RealAssert = Tester.Assert;
Tester.Assert = function(/**string*/ message, /**boolean*/ condition, /**SeSReportLink|SeSReportText|SeSReportImage|object[]|string*/ data, /**object*/ tags)
{
	if( g_assertMessage!=null )
	{
	
		message = g_assertMessage;
		g_assertMessage = null;
		
		
		if(message == "---")
		{
			return true;
		}
	}

	return Tester._RealAssert(message, condition, data, tags);
}

//#endregion ReportColumn