//<autogenerated> - Don't edit!

if(typeof(global)=='undefined') global=this;

function LisWeb_DoLogin(/**string*/usr, /**string*/pwd)
{
	var res = SeSPageObjectRvlInvoke(
		this,
		__dirname+"\\Test.sstest",
		__dirname+"\\Main.rvl.xlsx",
		"DoLogin",
		{
			usr: usr,
			pwd: pwd
		}
	);
	return res;
}

global.LisWeb_DoLogin = LisWeb_DoLogin;

var _paramInfoLisWeb_DoLogin={
	"_description": "DoAction description",
	"_type": "object",
	"_returns": "",
	"usr": {
		"type": "string",
		"defaultValue": "librarian"
	},
	"pwd": {
		"type": "string",
		"defaultValue": "librarian"
	}
};

global._paramInfoLisWeb_DoLogin = _paramInfoLisWeb_DoLogin;

function LisWeb_DoLogout()
{
	var res = SeSPageObjectRvlInvoke(
		this,
		__dirname+"\\Test.sstest",
		__dirname+"\\Main.rvl.xlsx",
		"DoLogout",
		{
		}
	);
	return res;
}

global.LisWeb_DoLogout = LisWeb_DoLogout;

var _paramInfoLisWeb_DoLogout={
	"_description": "DoLogout description",
	"_type": "object",
	"_returns": ""
};

global._paramInfoLisWeb_DoLogout = _paramInfoLisWeb_DoLogout;

function LisWeb_DoVerifyAuthorExists(/**string*/name)
{
	var res = SeSPageObjectRvlInvoke(
		this,
		__dirname+"\\Test.sstest",
		__dirname+"\\Main.rvl.xlsx",
		"DoVerifyAuthorExists",
		{
			name: name
		}
	);
	return res;
}

global.LisWeb_DoVerifyAuthorExists = LisWeb_DoVerifyAuthorExists;

var _paramInfoLisWeb_DoVerifyAuthorExists={
	"_description": "DoVerifyAuthorExists description",
	"_type": "object",
	"_returns": "",
	"name": {
		"type": "string",
		"defaultValue": "TestAuthor"
	}
};

global._paramInfoLisWeb_DoVerifyAuthorExists = _paramInfoLisWeb_DoVerifyAuthorExists;

function LisWeb_DoVerifyAuthorDoesNotExist(/**string*/name)
{
	var res = SeSPageObjectRvlInvoke(
		this,
		__dirname+"\\Test.sstest",
		__dirname+"\\Main.rvl.xlsx",
		"DoVerifyAuthorDoesNotExist",
		{
			name: name
		}
	);
	return res;
}

global.LisWeb_DoVerifyAuthorDoesNotExist = LisWeb_DoVerifyAuthorDoesNotExist;

var _paramInfoLisWeb_DoVerifyAuthorDoesNotExist={
	"_description": "DoVerifyAuthorDoesNotExist description",
	"_type": "object",
	"_returns": "",
	"name": {
		"type": "string",
		"defaultValue": "TestAuthor"
	}
};

global._paramInfoLisWeb_DoVerifyAuthorDoesNotExist = _paramInfoLisWeb_DoVerifyAuthorDoesNotExist;

SeSPageObject("LisWeb");
