//<autogenerated> - Don't edit!

function POMeasured_DoOneMinute()
{
	var res = SeSPageObjectRvlInvoke(
		this,
		__dirname+"\\Test.sstest",
		__dirname+"\\Main.rvl.xlsx",
		"DoOneMinute",
		{
		}
	);
	return res;
}

global.POMeasured_DoOneMinute = POMeasured_DoOneMinute;

var _paramInfoPOMeasured_DoOneMinute={
	"_description": "DoOneMinute description",
	"_type": "object",
	"_returns": ""
};

global._paramInfoPOMeasured_DoOneMinute = _paramInfoPOMeasured_DoOneMinute;

SeSPageObject("POMeasured");
